---

sudo: required
language: java

notifications:
  email:
    recipients:
      - podnov@gmail.com
    on_success: change
    on_failure: always

install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dcargo.skip=true -Dliquibase.shouldRun=false -B -V

before_script:
 - mysql -e 'create database queryinfo_test default character set utf8 default collate utf8_general_ci;'

script: mvn verify -Ptravis
